version: 2.1
orbs:
  go: circleci/go@1.8.0

  
jobs:
  build_and_test: # this can be any name you choose
    executor:
      name: go/default # Use the default executor from the orb
      tag: '1.20' # Specify a version tag
    steps:
      - checkout # checkout source code
      - go/load-cache # Load cached Go modules.
      - go/mod-download # Run 'go mod download'.
      - go/save-cache # Save Go modules to cache.
      - run:
          name: Run Go tests
          command: |
            go test ./...
  build_and_push:
    docker:
      - image: cimg/node:20.3.1
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Lets build and push image
          command: |
            version="build-$CIRCLE_BUILD_NUM"
            echo $version
            docker build -t nishanthvish/f1-app:$version .
            echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin
            docker push nishanthvish/f1-app:$version

  Update_manifest:
    docker:
      - image: cimg/base:2023.06
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Updating Manifest file 
          command: |
            TAG=$CIRCLE_BUILD_NUM
            ((TAG--))
            git clone https://github.com/Nishanth-Gowda/K8s-manifest.git
            git config --global user.email "vishu1332000@gmail.com"
            git config --global user.name "nishanth-gowda"
            pwd
            cd K8s-manifest
            pwd
            echo $TAG
            sed -i "s/build-.*/build-$TAG/g" manifests/deployment.yml
            cat manifests/deployment.yml
            git add .
            git commit -m "new build with imgTag build-$TAG"
            git config credential.helper 'cache --timeout=120'
            git push -q https://$GITHUB_PERSONAL_TOKEN@github.com/Nishanth-Gowda/K8s-manifest.git main 
workflows:
  GitOpsflow:
    jobs:
      - build_and_test
      - build_and_push
      - Update_manifest:
          requires:
            - build_and_push
